### PR TITLE
SDK-3304: Added extra node e2e tests

### PR DESCRIPTION
**Pull request by jholleran**
# Problem Details e2e testing

Added Node and Browser based e2e tests for the Problem Details feature.

# Checklist

- [x] All acceptance criteria are met.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [ ] New functions/types have been exported in `index.ts`, if applicable.
- [ ] New elements of the public API have appropriate API docs (including `@since` and `@example`).
- [ ] New modules (i.e. new `.ts` files) are listed in the `exports` field in `package.json`, if applicable.
- [ ] New modules (i.e. new `.ts` files) are listed in the `typedocOptions.entryPoints` field in `tsconfig.json`, if applicable.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Review by edwardsph — APPROVED** [review]
LGTM but is there a reason our tests don't check the message appears in `error.message`?

**Comment by jholleran** [comment]
I'll add that check to the tests

**Comment by jholleran** [comment]
@edwardsph I've made lots of changes here since your last review. Can you review it again please. Thanks.

**Review by edwardsph — APPROVED** [review]
LGTM with minor text changes in comments

**Pull request merged**
